/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/account/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_account_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_account_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_account_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify */
        post: operations["verify_api_v1_account_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend */
        post: operations["resend_api_v1_account_resend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot */
        post: operations["forgot_api_v1_account_forgot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset */
        post: operations["reset_api_v1_account_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_account_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_account_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/security": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Security */
        get: operations["security_api_v1_account_security_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/security/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activity */
        post: operations["activity_api_v1_account_security_activity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/security/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lock */
        post: operations["lock_api_v1_account_security_lock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/security/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unlock */
        post: operations["unlock_api_v1_account_security_unlock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/security/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Setup */
        post: operations["setup_api_v1_account_security_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/security/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change */
        post: operations["change_api_v1_account_security_change_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/security/timeout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Timeout */
        post: operations["timeout_api_v1_account_security_timeout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Providers */
        get: operations["providers_api_v1_data_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/providers/{provider}/credential": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Configure */
        post: operations["configure_api_v1_data_providers__provider__credential_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/providers/{provider}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check */
        post: operations["check_api_v1_data_providers__provider__check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit */
        post: operations["submit_api_v1_data_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_api_v1_data_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Progress */
        post: operations["progress_api_v1_jobs__job_id__progress_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/publish-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish */
        post: operations["publish_api_v1_jobs__job_id__publish_data_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Types */
        get: operations["data_types_api_v1_data_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog */
        get: operations["catalog_api_v1_data_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/catalog/{dataset_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_v1_data_catalog__dataset_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview */
        get: operations["preview_api_v1_data_versions__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Csv */
        post: operations["import_csv_api_v1_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim */
        post: operations["claim_api_v1_jobs_claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Heartbeat */
        post: operations["heartbeat_api_v1_jobs__job_id__heartbeat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/fail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fail */
        post: operations["fail_api_v1_jobs__job_id__fail_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish */
        post: operations["publish_api_v1_jobs__job_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Snapshots */
        get: operations["list_snapshots_api_v1_snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshots/{snapshot_id}/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bars */
        get: operations["bars_api_v1_snapshots__snapshot_id__bars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reference List */
        get: operations["reference_list_api_v1_reference_releases_get"];
        put?: never;
        /** Reference Publish */
        post: operations["reference_publish_api_v1_reference_releases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference/releases/{release_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reference Get */
        get: operations["reference_get_api_v1_reference_releases__release_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Bar */
        Bar: {
            /** Contract */
            contract: string;
            /**
             * Event Time
             * Format: date-time
             */
            event_time: string;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /**
             * Trading Day
             * Format: date
             */
            trading_day: string;
            /** Open */
            open: string;
            /** High */
            high: string;
            /** Low */
            low: string;
            /** Close */
            close: string;
            /** Volume */
            volume: number;
        };
        /** Capability */
        Capability: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Type Id */
            type_id: string;
            /** Exchanges */
            exchanges: string[];
            /**
             * Date Range
             * @default false
             */
            date_range: boolean;
            /**
             * Symbol Required
             * @default false
             */
            symbol_required: boolean;
            /** Description */
            description: string;
        };
        /** Claim */
        Claim: {
            /** Worker Id */
            worker_id: string;
        };
        /** ClaimedJob */
        ClaimedJob: {
            /** Id */
            id: string;
            /** Command Id */
            command_id: string;
            /** Kind */
            kind: string;
            /**
             * State
             * @enum {string}
             */
            state: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED" | "CANCELLED";
            /** Attempt */
            attempt: number;
            /** Created At */
            created_at: number;
            /** Worker Id */
            worker_id?: string | null;
            /** Lease Until */
            lease_until?: number | null;
            /** Error */
            error?: string | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Token */
            token: string;
        };
        /** Code */
        Code: {
            /** Email */
            email: string;
            /** Code */
            code: string;
        };
        /** Contract */
        "Contract-Input": {
            /** Id */
            id: string;
            /** Product Id */
            product_id: string;
            /** Delivery Month */
            delivery_month: string;
            /**
             * Listed At
             * Format: date-time
             */
            listed_at: string;
            /**
             * Last Trade At
             * Format: date-time
             */
            last_trade_at: string;
            /** Multiplier */
            multiplier: number | string;
            /** Tick Size */
            tick_size: number | string;
            provenance: components["schemas"]["Provenance"];
        };
        /** Contract */
        "Contract-Output": {
            /** Id */
            id: string;
            /** Product Id */
            product_id: string;
            /** Delivery Month */
            delivery_month: string;
            /**
             * Listed At
             * Format: date-time
             */
            listed_at: string;
            /**
             * Last Trade At
             * Format: date-time
             */
            last_trade_at: string;
            /** Multiplier */
            multiplier: string;
            /** Tick Size */
            tick_size: string;
            provenance: components["schemas"]["Provenance"];
        };
        /** ContractRules */
        "ContractRules-Input": {
            /** Contract Id */
            contract_id: string;
            /** Version */
            version: string;
            /**
             * Effective From
             * Format: date-time
             */
            effective_from: string;
            /** Effective Until */
            effective_until?: string | null;
            /** Margin Rate */
            margin_rate: number | string;
            open_fee: components["schemas"]["Fee-Input"];
            close_fee: components["schemas"]["Fee-Input"];
            close_today_fee: components["schemas"]["Fee-Input"];
            /** Requires Close Today */
            requires_close_today: boolean;
            /** Limit Ratio */
            limit_ratio?: number | string | null;
            provenance: components["schemas"]["Provenance"];
        };
        /** ContractRules */
        "ContractRules-Output": {
            /** Contract Id */
            contract_id: string;
            /** Version */
            version: string;
            /**
             * Effective From
             * Format: date-time
             */
            effective_from: string;
            /** Effective Until */
            effective_until?: string | null;
            /** Margin Rate */
            margin_rate: string;
            open_fee: components["schemas"]["Fee-Output"];
            close_fee: components["schemas"]["Fee-Output"];
            close_today_fee: components["schemas"]["Fee-Output"];
            /** Requires Close Today */
            requires_close_today: boolean;
            /** Limit Ratio */
            limit_ratio?: string | null;
            provenance: components["schemas"]["Provenance"];
        };
        /** CredentialUpdate */
        CredentialUpdate: {
            /**
             * Token
             * Format: password
             */
            token: string;
        };
        /** DataField */
        DataField: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Unit */
            unit?: string | null;
        };
        /** Email */
        Email: {
            /** Email */
            email: string;
        };
        /** Failure */
        Failure: {
            /** Token */
            token: string;
            /** Error */
            error: string;
        };
        /** Fee */
        "Fee-Input": {
            /**
             * Per Lot
             * @default 0
             */
            per_lot: number | string;
            /**
             * Notional Rate
             * @default 0
             */
            notional_rate: number | string;
        };
        /** Fee */
        "Fee-Output": {
            /**
             * Per Lot
             * @default 0
             */
            per_lot: string;
            /**
             * Notional Rate
             * @default 0
             */
            notional_rate: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportRequest */
        ImportRequest: {
            /** Command Id */
            command_id: string;
            /** Source */
            source: string;
            /** Csv */
            csv: string;
        };
        /** Job */
        Job: {
            /** Id */
            id: string;
            /** Command Id */
            command_id: string;
            /** Kind */
            kind: string;
            /**
             * State
             * @enum {string}
             */
            state: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED" | "CANCELLED";
            /** Attempt */
            attempt: number;
            /** Created At */
            created_at: number;
            /** Worker Id */
            worker_id?: string | null;
            /** Lease Until */
            lease_until?: number | null;
            /** Error */
            error?: string | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
        };
        /** Lease */
        Lease: {
            /** Token */
            token: string;
        };
        /** LockTimeout */
        LockTimeout: {
            /** Seconds */
            seconds: number;
        };
        /** Login */
        Login: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** Manifest */
        Manifest: {
            /** Frequency */
            frequency?: string | null;
            /** Time Semantics */
            time_semantics?: string | null;
            /** Dataset Id */
            dataset_id?: string | null;
            /** Schema Version */
            schema_version: number;
            /** Rows */
            rows: number;
            /** Checksum */
            checksum: string;
            /** Contracts */
            contracts: string[];
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Uri */
            uri: string;
            /** Source */
            source: string;
            /**
             * State
             * @constant
             */
            state: "PUBLISHED";
        };
        /** PinInput */
        PinInput: {
            /** Pin */
            pin: string;
            /** Expected */
            expected?: number | null;
            /** Password */
            password?: string | null;
        };
        /** Product */
        Product: {
            /** Id */
            id: string;
            /**
             * Exchange
             * @enum {string}
             */
            exchange: "SHFE" | "DCE" | "CZCE" | "CFFEX" | "INE" | "GFEX";
            /** Name */
            name: string;
            /** Currency */
            currency: string;
            provenance: components["schemas"]["Provenance"];
        };
        /** Progress */
        Progress: {
            /** Token */
            token: string;
            /** Completed */
            completed: number;
            /** Total */
            total: number;
        };
        /** Provenance */
        Provenance: {
            /** Source */
            source: string;
            /** Source Version */
            source_version: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
        };
        /** ProviderStatus */
        ProviderStatus: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
            /**
             * Api Version
             * @default 1
             */
            api_version: number;
            /** Capabilities */
            capabilities: components["schemas"]["Capability"][];
            /** Configured */
            configured: boolean;
            /** Credential Error */
            credential_error?: string | null;
        };
        /** ReferenceCatalog */
        "ReferenceCatalog-Input": {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Products */
            products: components["schemas"]["Product"][];
            /** Contracts */
            contracts: components["schemas"]["Contract-Input"][];
            /** Calendars */
            calendars: components["schemas"]["SessionCalendar"][];
            /** Rules */
            rules: components["schemas"]["ContractRules-Input"][];
        };
        /** ReferenceCatalog */
        "ReferenceCatalog-Output": {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Products */
            products: components["schemas"]["Product"][];
            /** Contracts */
            contracts: components["schemas"]["Contract-Output"][];
            /** Calendars */
            calendars: components["schemas"]["SessionCalendar"][];
            /** Rules */
            rules: components["schemas"]["ContractRules-Output"][];
        };
        /** ReferenceRelease */
        ReferenceRelease: {
            /** Id */
            id: string;
            /** Published At */
            published_at: number;
            catalog: components["schemas"]["ReferenceCatalog-Output"];
        };
        /** ReferenceSummary */
        ReferenceSummary: {
            /** Id */
            id: string;
            /** Published At */
            published_at: number;
            /** Products */
            products: number;
            /** Contracts */
            contracts: number;
            /** Sources */
            sources: string[];
        };
        /** Registration */
        Registration: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Pin */
            pin: string;
            /**
             * Country Code
             * @default
             */
            country_code: string;
            /**
             * Phone
             * @default
             */
            phone: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
        };
        /** Reset */
        Reset: {
            /** Email */
            email: string;
            /** Code */
            code: string;
            /** Password */
            password: string;
        };
        /** Retry */
        Retry: {
            /** Command Id */
            command_id: string;
        };
        /** SecurityState */
        SecurityState: {
            /** Pin Required */
            pin_required: boolean;
            /** Locked */
            locked: boolean;
            /** Timeout Seconds */
            timeout_seconds: number;
            /** Remaining Seconds */
            remaining_seconds: number;
            /** Revision */
            revision: number;
            /** Retry After */
            retry_after: number;
        };
        /** Session */
        Session: {
            /**
             * Opens At
             * Format: date-time
             */
            opens_at: string;
            /**
             * Closes At
             * Format: date-time
             */
            closes_at: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "day" | "night" | "auction";
        };
        /** SessionCalendar */
        SessionCalendar: {
            /** Product Id */
            product_id: string;
            /** Version */
            version: string;
            /**
             * Timezone
             * @default Asia/Shanghai
             * @constant
             */
            timezone: "Asia/Shanghai";
            /** Days */
            days: components["schemas"]["TradingDay"][];
            provenance: components["schemas"]["Provenance"];
        };
        /** Snapshot */
        Snapshot: {
            /** Id */
            id: string;
            /** Job Id */
            job_id: string;
            manifest: components["schemas"]["Manifest"];
        };
        /** SyncRequest */
        SyncRequest: {
            /** Command Id */
            command_id: string;
            /** Provider */
            provider: string;
            /** Dataset */
            dataset: string;
            /** Exchange */
            exchange: string;
            /**
             * Symbol
             * @default
             */
            symbol: string;
            /** Start */
            start?: string | null;
            /** End */
            end?: string | null;
        };
        /** TradingDay */
        TradingDay: {
            /**
             * Trading Day
             * Format: date
             */
            trading_day: string;
            /**
             * Sessions
             * @default []
             */
            sessions: components["schemas"]["Session"][];
            /**
             * Closed
             * @default false
             */
            closed: boolean;
        };
        /** TypeManifest */
        TypeManifest: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Domain */
            domain: string;
            /** Domain Label */
            domain_label: string;
            /**
             * Shape
             * @enum {string}
             */
            shape: "table" | "timeseries" | "document" | "graph" | "artifact";
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /**
             * Api Version
             * @default 1
             */
            api_version: number;
            /** Frequency */
            frequency: string;
            /** Primary Key */
            primary_key: string[];
            /** Time Field */
            time_field?: string | null;
            /** Time Semantics */
            time_semantics: string;
            /** Fields */
            fields?: components["schemas"]["DataField"][];
            /** Description */
            description: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    capabilities_api_v1_account_capabilities_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_account_register_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Registration"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_account_login_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_api_v1_account_verify_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Code"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_api_v1_account_resend_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Email"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_api_v1_account_forgot_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Email"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_api_v1_account_reset_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reset"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_account_me_get: {
        parameters: {
            query?: never;
            header?: {
                "x-account-session"?: string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_account_logout_post: {
        parameters: {
            query?: never;
            header?: {
                "x-account-session"?: string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    security_api_v1_account_security_get: {
        parameters: {
            query?: never;
            header?: {
                "x-account-session"?: string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activity_api_v1_account_security_activity_post: {
        parameters: {
            query?: never;
            header?: {
                "x-account-session"?: string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lock_api_v1_account_security_lock_post: {
        parameters: {
            query?: never;
            header?: {
                "x-account-session"?: string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unlock_api_v1_account_security_unlock_post: {
        parameters: {
            query?: never;
            header?: {
                "x-account-session"?: string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setup_api_v1_account_security_setup_post: {
        parameters: {
            query?: never;
            header?: {
                "x-account-session"?: string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_api_v1_account_security_change_post: {
        parameters: {
            query?: never;
            header?: {
                "x-account-session"?: string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeout_api_v1_account_security_timeout_post: {
        parameters: {
            query?: never;
            header?: {
                "x-account-session"?: string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LockTimeout"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    providers_api_v1_data_providers_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-account-session"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderStatus"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    configure_api_v1_data_providers__provider__credential_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-account-session"?: string;
            };
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_api_v1_data_providers__provider__check_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-account-session"?: string;
            };
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_api_v1_data_sync_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-account-session"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_api_v1_data_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-account-session"?: string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Retry"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    progress_api_v1_jobs__job_id__progress_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Progress"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_api_v1_jobs__job_id__publish_data_post: {
        parameters: {
            query?: never;
            header: {
                "x-lease-token": string;
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_types_api_v1_data_types_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-account-session"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeManifest"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalog_api_v1_data_catalog_get: {
        parameters: {
            query?: {
                domain?: string;
                type_id?: string;
                source?: string;
                layer?: string;
                search?: string;
                offset?: number;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-account-session"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_v1_data_catalog__dataset_id__versions_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-account-session"?: string;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_v1_data_versions__version_id__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-account-session"?: string;
            };
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-account-session"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_csv_api_v1_imports_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-account-session"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_api_v1_jobs_claim_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Claim"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimedJob"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heartbeat_api_v1_jobs__job_id__heartbeat_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Lease"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fail_api_v1_jobs__job_id__fail_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Failure"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-account-session"?: string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_api_v1_jobs__job_id__publish_post: {
        parameters: {
            query?: never;
            header: {
                "x-lease-token": string;
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_api_v1_snapshots_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-account-session"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bars_api_v1_snapshots__snapshot_id__bars_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-account-session"?: string;
            };
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bar"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reference_list_api_v1_reference_releases_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
                "x-account-session"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reference_publish_api_v1_reference_releases_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-account-session"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReferenceCatalog-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceRelease"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reference_get_api_v1_reference_releases__release_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-account-session"?: string;
            };
            path: {
                release_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceRelease"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
