"""Generate public task states from the authoritative Rust state machine."""

import argparse
import json
from pathlib import Path

from asterion_bindings.tasks import task_rule


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    states = task_rule("contract")["states"]
    source = (
        "# Generated by scripts/generate_task_contract.py; do not edit.\n"
        "from typing import Literal\n\n"
        "TaskState = Literal[" + ", ".join(json.dumps(state) for state in states) + "]\n"
    )
    target = (
        Path(__file__).resolve().parents[1] / "bindings/python/asterion_bindings/tasks_generated.py"
    )
    if args.check:
        if not target.exists() or target.read_text() != source:
            raise SystemExit("Task contract generated bindings are stale")
    else:
        target.write_text(source)


if __name__ == "__main__":
    main()
