"""Generate all language bindings from the current wire contract; --check detects drift."""

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
schema = json.loads((ROOT / "contracts/communication.json").read_text())


def kind(value, lang):
    if "$ref" in value:
        return value["$ref"].split("/")[-1]
    if "anyOf" in value:
        types = [kind(v, lang) for v in value["anyOf"]]
        return " | ".join(types) if lang != "rs" else "serde_json::Value"
    if value.get("type") == "array":
        inner = kind(value["items"], lang)
        return {"py": f"list[{inner}]", "ts": f"Array<{inner}>", "rs": f"Vec<{inner}>"}[lang]
    t = value.get("type")
    if isinstance(t, list):
        types = [kind({"type": v}, lang) for v in t]
        return " | ".join(types) if lang != "rs" else "serde_json::Value"
    if lang == "ts" and "enum" in value:
        return " | ".join(json.dumps(v) for v in value["enum"])
    if lang == "py" and "enum" in value:
        return "Literal[" + ", ".join(repr(v) for v in value["enum"]) + "]"
    return {
        "py": {"string": "str", "integer": "int", "null": "None", "object": "dict[str, Any]"},
        "ts": {
            "string": "string",
            "integer": "number",
            "null": "null",
            "object": "Record<string, unknown>",
        },
        "rs": {
            "string": "String",
            "integer": "u64",
            "null": "serde_json::Value",
            "object": "serde_json::Map<String, serde_json::Value>",
        },
    }[lang].get(t, {"py": "Any", "ts": "unknown", "rs": "serde_json::Value"}[lang])


outputs = {}
py = [
    "# Generated by scripts/generate_communication.py; do not edit.",
    "# ruff: noqa",
    "from typing import Any, Literal, TypedDict",
    "import json",
    "SCHEMA = json.loads(" + repr(json.dumps(schema, ensure_ascii=False)) + ")",
]
ts = [
    "// Generated by scripts/generate_communication.py; do not edit.",
    "export const schema = " + json.dumps(schema, ensure_ascii=False) + ";",
]
rs = [
    "// Generated by scripts/generate_communication.py; do not edit.",
    "#![allow(dead_code)]",
    "use serde::{Serialize, Deserialize};",
    'pub const SCHEMA: &str = r##"' + json.dumps(schema, ensure_ascii=False) + '"##;',
]
for name, definition in schema["$defs"].items():
    py.append(f"class {name}(TypedDict):")
    ts.append(f"export interface {name} {{")
    rs.extend(
        [
            "#[derive(Debug, Clone, Serialize, Deserialize)]",
            "#[serde(deny_unknown_fields)]",
            f"pub struct {name} {{",
        ]
    )
    for field, value in definition["properties"].items():
        py.append(f"    {field}: {kind(value, 'py')}")
        ts.append(f"  {field}: {kind(value, 'ts')};")
        if value.get("type") == "integer":
            rs.append(
                '    #[serde(deserialize_with = "crate::communication::deserialize_unsigned")]'
            )
        rs.append(f"    pub {field}: {kind(value, 'rs')},")
    ts.append("}")
    rs.append("}")
outputs["src/asterion_plugin_sdk/wire.py"] = "\n".join(py) + "\n"
outputs["src/asterion_plugin_sdk/wire.py"] = subprocess.run(
    [sys.executable, "-m", "ruff", "format", "--stdin-filename", "wire.py", "-"],
    input=outputs["src/asterion_plugin_sdk/wire.py"],
    text=True,
    capture_output=True,
    check=True,
).stdout
outputs["bindings/typescript/src/wire.generated.ts"] = "\n".join(ts) + "\n"
outputs["foundation/src/wire_generated.rs"] = "\n".join(rs) + "\n"
parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
for path, content in outputs.items():
    target = ROOT / path
    if args.check:
        if not target.exists() or target.read_text() != content:
            raise SystemExit(f"Stale communication binding: {path}")
    else:
        target.write_text(content)
