"""Generate Python DTO fields from authoritative Rust schemas; never copy domain rules."""

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def annotation(schema):
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return f"Literal[{schema['const']!r}]"
    if "enum" in schema:
        return "Literal[" + ", ".join(repr(item) for item in schema["enum"]) + "]"
    if "anyOf" in schema:
        return " | ".join(annotation(item) for item in schema["anyOf"])
    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(annotation(schema | {"type": item}) for item in kind)
    if kind == "array":
        return f"tuple[{annotation(schema['items'])}, ...]"
    if kind == "object" and isinstance(schema.get("additionalProperties"), dict):
        return f"dict[str, {annotation(schema['additionalProperties'])}]"
    if kind == "string":
        return {"date": "date_type", "date-time": "AwareDatetime", "decimal": "Decimal"}.get(
            schema.get("format"), "str"
        )
    if kind in {"integer", "number", "boolean", "null"}:
        return {"integer": "int", "number": "float", "boolean": "StrictBool", "null": "None"}[kind]
    raise ValueError(f"Unsupported Rust schema shape: {schema}")


def generate(domain, schema, inherited=None):
    definitions = schema["$defs"]
    lines = [
        "# Generated by scripts/generate_domain_models.py from Rust; do not edit.",
        "# ruff: noqa",
        "from __future__ import annotations",
        "from datetime import date as date_type",
        "from decimal import Decimal",
        "from typing import ClassVar, Literal",
        "from pydantic import AwareDatetime, ConfigDict, Field, StrictBool",
        f"from ._{domain}_binding import *",
        "",
    ]
    inherited = inherited or {}
    for owner, names in inherited.items():
        lines.append(f"from .{owner} import " + ", ".join(sorted(names)))
    excluded = {name for names in inherited.values() for name in names}
    base = {
        "catalog": "CatalogModel",
        "calendar": "CalendarModel",
        "rules": "RulesModel",
        "roles": "RolesModel",
        "market_feed": "MarketFeedModel",
        "data_store": "DataStoreModel",
        "execution": "ExecutionModel",
        "connections": "ConnectionsModel",
    }[domain]
    mixins = {
        "ReferenceCatalog": "CatalogOps",
        "SourceIdentity": "SourceOps",
        "ImportIdentity": "ImportOps",
        "TimeSpec": "CalendarOps",
        "RuleSpec": "RulesOps",
        "RulePeriod": "RulePeriodOps",
        "SettlementBasis": "SettlementOps",
        "RoleCalendar": "OpeningOps",
        "ComputedRoleIndex": "ComputedRoleOps",
    }
    models = []
    for name, definition in definitions.items():
        if name in excluded:
            continue
        if definition.get("type") != "object":
            lines.append(f"{name} = {annotation(definition)}")
            continue
        models.append(name)
        bases = f"{mixins[name]}, {base}" if name in mixins else base
        lines.extend(
            [
                "",
                f"class {name}({bases}):",
                f"    _native_model: ClassVar[str] = {name!r}",
                f"    _native_fields: ClassVar[frozenset[str]] = frozenset({tuple(definition.get('properties', {}))!r})",
            ]
        )
        if definition.get("x-strip-whitespace"):
            lines.append("    model_config = ConfigDict(str_strip_whitespace=True)")
        for field, value in definition.get("properties", {}).items():
            required = field in definition.get("required", [])
            if not required and "default" not in value:
                raise ValueError(
                    f"{name}.{field} must explicitly declare required/default semantics"
                )
            constraints = {}
            if not required:
                constraints["default"] = value["default"]
            for source, target in (
                ("minLength", "min_length"),
                ("maxLength", "max_length"),
                ("minItems", "min_length"),
                ("maxItems", "max_length"),
                ("minimum", "ge"),
                ("maximum", "le"),
                ("exclusiveMinimum", "gt"),
                ("exclusiveMaximum", "lt"),
                ("pattern", "pattern"),
            ):
                if source in value:
                    constraints[target] = value[source]
            suffix = ""
            if constraints:
                suffix = " = Field(" + ", ".join(f"{k}={v!r}" for k, v in constraints.items()) + ")"
            lines.append(f"    {field}: {annotation(value)}{suffix}")
    lines.extend(["", *[f"{name}.model_rebuild()" for name in models], ""])
    content = "\n".join(lines)
    return subprocess.run(
        [sys.executable, "-m", "ruff", "format", "--stdin-filename", f"{domain}.py", "-"],
        input=content,
        text=True,
        capture_output=True,
        check=True,
    ).stdout


def main():
    from asterion_bindings._call import invoke

    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    known = {}
    for domain in (
        "catalog",
        "calendar",
        "rules",
        "roles",
        "market_feed",
        "connections",
        "data_store",
        "execution",
    ):
        schema = invoke(domain, "schema", {})
        inherited = {}
        if domain in {"rules", "roles", "execution"}:
            for name in schema["$defs"]:
                if name in known:
                    inherited.setdefault(known[name], []).append(name)
        target = ROOT / f"bindings/python/asterion_bindings/{domain}.py"
        content = generate(domain, schema, inherited)
        if args.check:
            if not target.exists() or target.read_text() != content:
                raise SystemExit(f"Stale domain binding: {target.relative_to(ROOT)}")
        else:
            target.write_text(content)
        for name in schema["$defs"]:
            known.setdefault(name, domain)
        # A reviewable contract snapshot, generated from the same Rust definition.
        target = ROOT / f"contracts/{domain}.schema.json"
        content = json.dumps(schema, ensure_ascii=False, sort_keys=True, indent=2) + "\n"
        if args.check:
            if not target.exists() or target.read_text() != content:
                raise SystemExit(f"Stale domain schema: {target.relative_to(ROOT)}")
        else:
            target.write_text(content)


if __name__ == "__main__":
    main()
