from collections.abc import Callable
from pathlib import Path

from pyarrow import RecordBatch

class NativeDataScan:
    def __init__(
        self,
        files: ReadFilesHandle,
        storage: StorageScope,
        lifetimes: list[HostHandle | ExecutionHandle],
        version_json: str,
        request_json: str,
    ) -> None: ...
    def next_batch(self) -> RecordBatch | None: ...
    def close(self) -> None: ...
    def metrics(self) -> dict[str, int | bool]: ...

def invoke(module: str, operation: str, input: str) -> str: ...

class ConnectionsError(ValueError):
    category: str
    retryable: bool

class ConnectionEmitter:
    def __call__(self, kind: str, value: object) -> None: ...

class ConnectionReadCancellation:
    def is_set(self) -> bool: ...

class Connections:
    def __init__(
        self,
        path: str,
        secrets: object,
        owners: str,
        dispatch: Callable[[str, int, str, object], None],
    ) -> None: ...
    def initialize(self, descriptors: str, sources: list[object]) -> None: ...
    def profiles(self) -> list[str]: ...
    def profile(self, id: str) -> str: ...
    def channel(self, id: str, channel: str) -> str: ...
    def supports(self, id: str, feature: str) -> bool: ...
    def active_id(self) -> str | None: ...
    def view(self, id: str) -> str: ...
    def snapshot(self) -> str: ...
    def save(self, body: str) -> str: ...
    def delete(self, id: str, revision: int) -> str: ...
    def select(self, id: str) -> str: ...
    def connect(self, id: str) -> str: ...
    def disconnect(self, id: str) -> str: ...
    def subscribe(self, id: str, subscriptions: str) -> None: ...
    def read(self, id: str, kind: str, cancel: object) -> str: ...
    def close(self) -> None: ...

class MarketQuotes:
    def __init__(self) -> None: ...
    def bind(self, revision: int) -> None: ...
    def subscriptions(self, value: str) -> None: ...
    def ingest(
        self, generation: int, current: int, ready: bool, value: str, now: float
    ) -> None: ...
    def subscription_error(
        self, generation: int, current: int, symbol: str, detail: str
    ) -> None: ...
    def connection_event(self, generation: int, current: int, kind: str) -> None: ...
    def snapshot(self, current: int, ready: bool, now: float) -> str: ...

class EnvironmentLease:
    def __init__(self, host: object, backup_directory: object, layout: str, wait: bool) -> None: ...
    def close(self) -> None: ...
    def active(self) -> Path: ...
    def status(self) -> str: ...
    def recover(self, callback: object) -> None: ...
    def switch(self, target: object, callback: object) -> str: ...

class ReadFilesHandle:
    def __init__(self, root: object, read_bytes: int, scan_entries: int) -> None: ...
    def read(self, name: str) -> bytes: ...
    def digest(self, name: str) -> str: ...
    def scan(self, name: str, suffix: str) -> list[str]: ...

def data_store_merge(
    store: ArtifactStoreHandle,
    lifetimes: list[HostHandle | ExecutionHandle],
    request_json: str,
) -> str: ...
def data_store_read_index(
    store: ArtifactStoreHandle,
    lifetimes: list[HostHandle | ExecutionHandle],
    version_json: str,
) -> str: ...
def data_store_verify_version(
    store: ArtifactStoreHandle,
    lifetimes: list[HostHandle | ExecutionHandle],
    version_json: str,
) -> str: ...
def data_store_read_partition(
    store: ArtifactStoreHandle,
    lifetimes: list[HostHandle | ExecutionHandle],
    partition_json: str,
) -> RecordBatch: ...

class ArtifactStoreHandle:
    def __init__(self, root: object, max_bytes: int, writable: bool) -> None: ...
    def verify(self, name: str, sha256: str, size: int | None = None) -> None: ...
    def put(self, name: str, content: bytes) -> tuple[str, str, int]: ...
    def put_addressed(
        self, directory: str, suffix: str, content: bytes
    ) -> tuple[str, str, int]: ...
    def read(self, name: str, sha256: str, size: int | None = None) -> bytes: ...

class FileLockHandle:
    def __init__(self, path: object, blocking: bool, timeout: float | None = None) -> None: ...
    def close(self) -> None: ...

class FilePublicationError(OSError):
    published: bool

def file_digest(path: object) -> str: ...
def trusted_tree_digest(
    roots: list[Path],
    excluded_components: list[str],
    excluded_suffixes: list[str],
    max_entries: int,
    max_bytes: int,
) -> str: ...
def file_atomic_write(path: object, content: bytes, replace: bool) -> None: ...

class StorageScope:
    def __init__(self, database: int, writable: list[int], readable: list[int]) -> None: ...
    def check(self) -> None: ...
    def guarded(self, lifetime: HostHandle | ExecutionHandle) -> StorageScope: ...
    def close(self) -> None: ...
    def initialize(self, tables: list[int]) -> None: ...
    def begin(self, write: bool) -> StorageTransaction: ...
    def join(self, parent: StorageTransaction, write: bool) -> StorageTransaction: ...

class StorageTransaction:
    def bind(self, connection: NativeConnection) -> None: ...
    def check(self) -> None: ...
    def writable(self) -> bool: ...
    def require_write(self) -> None: ...
    def commit_ready(self) -> None: ...
    def close(self) -> None: ...
    def abort(self) -> None: ...
    def authorize(self, statement: str) -> None: ...

def storage_preflight(expected: str, actual: str) -> None: ...
def storage_ownership(core: list[str], owners: list[list[str]]) -> None: ...

class Supervisor:
    def __init__(self, configuration: str) -> None: ...
    def request_stop(self) -> None: ...
    def run(self) -> None: ...

class TaskHandlerDeclaration:
    def __init__(self, kind: str, publish_suffix: str, requests: str) -> None: ...
    def requests(self) -> TaskRequestScope: ...

class TaskRequestScope:
    def authorize(self, suffix: str) -> None: ...
    def close(self) -> None: ...

class TaskHandlerRegistry:
    def __init__(self) -> None: ...
    def register(self, declaration: TaskHandlerDeclaration) -> int: ...
    def get(self, kind: str) -> int: ...
    def worker_grants(self) -> str: ...

class NativeDatabaseError(Exception): ...

def database_sqlite_version() -> tuple[int, int, int]: ...

class RestoreScope:
    def __init__(self) -> None: ...
    def operation(self, action: Callable[[], object]) -> RestoreOperation: ...
    def verify(self) -> None: ...
    def close(self) -> None: ...

class RestoreOperation:
    def __call__(self) -> None: ...

class BackupMetrics:
    def __init__(self) -> None: ...
    def add(self, value: object) -> None: ...
    def counts(self) -> dict[str, int]: ...

def recovery_inputs(expected: list[str], provided: list[str], restore: bool) -> None: ...

class NativeDatabase:
    def identity(self) -> int: ...
    def __init__(self, configuration: str, pool_size: int, wait_seconds: float) -> None: ...
    def connect(self) -> NativeConnection: ...
    def dispose(self) -> None: ...

class NativeConnection:
    def begin_write(self) -> None: ...
    def begin(self) -> None: ...
    def execute(self, sql: str, parameters: str, stream: bool = False) -> NativeCursor: ...
    def executemany(self, sql: str, parameters: str) -> NativeCursor: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
    @property
    def autocommit(self) -> bool: ...
    @autocommit.setter
    def autocommit(self, value: bool) -> None: ...
    def table_names(self) -> str: ...
    def observe_schema(self) -> str: ...

class NativeCursor:
    def description(self) -> str: ...
    @property
    def rowcount(self) -> int: ...
    @property
    def lastrowid(self) -> int | None: ...
    def fetchmany(self, size: int) -> str: ...
    def close(self) -> None: ...

def communication_validate(name: str, value: object) -> None: ...
def communication_loads(raw: str) -> str: ...
def communication_context(timeout: float, raw_parent: str | None) -> str: ...
def communication_continue(correlation_id: str, causation_id: str, timeout: float) -> str: ...
def communication_active(value: object) -> str: ...
def communication_ingress(raw: str | None, timeout: float) -> str: ...
def communication_call(
    timeout: float, raw_parent: str | None, kind: str, contract: str, payload: object
) -> str: ...
def communication_reply(trace: object, result: object, error: object) -> str: ...
def communication_result(trace: object, response: object) -> str: ...
def event_topic_validate(value: str) -> None: ...
def diagnostics_recent(root: object, digest: str) -> str: ...
def diagnostic_event(root: object, component: str, code: str, context: object = None) -> None: ...
def diagnostics_events(root: object) -> str: ...

class DiagnosticsObservation:
    def __init__(self, root: object, digest: str) -> None: ...
    def call(self, method: str) -> None: ...
    def finish(self, code: str = "success") -> None: ...

class EventRegistry:
    def __init__(self, database: int, topics: str) -> None: ...
    def check_topic(self, topic: str) -> None: ...
    def read_path(self, topic: str, method: str) -> str: ...
    def publisher(self, owner: str, topics: str) -> EventPublisher: ...
    def read_plan(self, request: str) -> str: ...
    def publish_host(
        self, connection: NativeConnection, topic: str, stream: str, payload: str, trace: str
    ) -> str: ...
    def read(self, connection: NativeConnection, plan: str) -> str: ...

class EventPublisher:
    def check(self, transaction: StorageTransaction, topic: str) -> None: ...
    def guarded(self, handle: HostHandle) -> EventPublisher: ...
    def publish(
        self, transaction: StorageTransaction, topic: str, stream: str, payload: str, trace: str
    ) -> str: ...

def event_journal_validate(connection: NativeConnection) -> int: ...

class TaskConflict(ValueError): ...

class TaskRepository:
    def __init__(self, database: int, topic: str) -> None: ...
    def run(self, connection: NativeConnection, request: str, trace: str) -> str: ...
    def granted(self, kinds: list[str]) -> TaskGrant: ...

class TaskGrant:
    def submit(self, connection: NativeConnection, record: str, trace: str) -> str: ...
    def run(self, transaction: StorageTransaction, request: str, trace: str) -> str: ...

class ArchiveHandle:
    def __init__(self, content: bytes, policy_json: str) -> None: ...
    @property
    def digest(self) -> str: ...
    @property
    def names(self) -> list[str]: ...
    def read(self, name: str) -> bytes: ...
    def publish(self, root: object) -> None: ...
    @staticmethod
    def load(root: object, digest: str, policy_json: str) -> ArchiveHandle: ...

class TaskProcess:
    def __init__(self, arguments: list[str], context: str, request: bytes, limits: str) -> None: ...
    def poll(self, timeout: float) -> bool: ...
    def take_result(self) -> TaskArtifact: ...
    def close(self) -> None: ...

class TaskArtifact:
    def metadata(self) -> str: ...
    def read_chunk(self) -> bytes: ...
    def close(self) -> None: ...

def task_process_serve(callback: Callable[[bytes], tuple[bytes, str, str | None]]) -> None: ...

class ProcessTransport:
    def __init__(
        self, arguments: list[str], cwd: object, timeout: float, authorized: object
    ) -> None: ...
    def call(self, request: str) -> str: ...
    def close(self) -> None: ...

def transport_invoke(
    arguments: list[str], request: str, cwd: object = None, authorized: object = None
) -> str: ...
def transport_serve(dispatch: object) -> None: ...
def transport_child_limits() -> None: ...

class DomainHandle:
    def __init__(self, module: str, model: str, value: str) -> None: ...
    def call(self, operation: str, value: str) -> str: ...

class HostHandle:
    def check(self) -> None: ...

class ExecutionHandle:
    def check(self) -> None: ...

class ExecutionScope:
    def __init__(self, declarations: str, grants: str) -> None: ...
    def resource(self, value: str) -> ExecutionHandle: ...
    def close(self) -> None: ...

class PluginHost:
    def context(self, owner: str) -> HostHandle: ...
    def __init__(self, manifests: str) -> None: ...
    @property
    def order(self) -> list[str]: ...
    @property
    def type_order(self) -> list[str]: ...
    @property
    def state(self) -> str: ...
    def begin(self, grants: str) -> None: ...
    def next_activation(self) -> str | None: ...
    def activated(self, id: str, exports: str) -> None: ...
    def returned(self, id: str) -> None: ...
    def finish(self) -> None: ...
    def close(self) -> list[str]: ...
    def resource(self, owner: str, value: str) -> HostHandle: ...
    def capability(self, owner: str, value: str) -> HostHandle: ...
    def export(self, value: str) -> HostHandle: ...
    def observation(self, owner: str, name: str) -> HostHandle: ...
    def plugin(self, owner: str) -> HostHandle: ...

class SecretError(ValueError): ...

class SecretHandle:
    def __init__(self, master: str, encryption: bytes, fingerprint: bytes) -> None: ...
    def encrypt(self, content: bytes) -> bytes: ...
    def decrypt(self, content: bytes) -> bytes: ...
    def fingerprint(self, content: bytes) -> str: ...

class StagedDirectory:
    def __init__(self, destination: object, max_entries: int) -> None: ...
    @property
    def path(self) -> Path: ...
    def commit(self) -> None: ...
    def preserve(self) -> Path: ...
    def close(self) -> None: ...

class FileArchiveWriter:
    def __init__(
        self,
        source: object,
        destination: object,
        roots: list[str],
        excludes: list[str],
        policy_json: str,
        metadata_name: str,
    ) -> None: ...
    def catalog(self) -> str: ...
    def commit(self, metadata: bytes) -> str: ...
    def close(self) -> None: ...

class FileArchiveReader:
    def __init__(self, path: object, policy_json: str, metadata_name: str) -> None: ...
    def metadata(self) -> bytes: ...
    def digest(self) -> str: ...
    def extract(self, stage: StagedDirectory, files_json: str, directories_json: str) -> None: ...
    def close(self) -> None: ...

class ExecutionFactory:
    def __init__(self, lifetimes: list[HostHandle | ExecutionHandle]) -> None: ...
    def create(
        self, config: str, lifetimes: list[HostHandle | ExecutionHandle]
    ) -> DailyAccount: ...
    def close(self) -> None: ...

class DailyAccount:
    def begin_day(self, bar: str) -> str: ...
    def close_intent(self, long: bool) -> None: ...
    def finish(self) -> str: ...
    def close(self) -> None: ...

def data_catalog_list(connection: NativeConnection, query: str) -> str: ...
def data_catalog_history(
    connection: NativeConnection, dataset_id: str, offset: int, limit: int
) -> str: ...
def data_catalog_hierarchy(connection: NativeConnection, include_archived: bool) -> str: ...
def data_version_preview(
    connection: NativeConnection, root: object, version_id: str, offset: int, limit: int
) -> str: ...
def data_types() -> str: ...
def data_type_validate(type_id: str, rows: str) -> None: ...
def data_type_coverage(
    type_id: str, rows: int, start: str | None = None, end: str | None = None
) -> str: ...
def data_import_execute(
    connection: NativeConnection, root: object, job_id: str, token: str, now: float
) -> str: ...
def data_snapshot_bars(
    connection: NativeConnection, root: object, snapshot_id: str, limit: int
) -> str: ...
def data_daily_chart(rows: str, available_at: str) -> tuple[bytes, str]: ...
def data_provider_manifests() -> str: ...
def data_provider_plan(provider: str, request: str) -> str: ...
def data_provider_check_plan(request: str, parts: str) -> None: ...
def data_provider_probe(provider: str, configuration: str) -> str: ...
def data_provider_fetch(provider: str, partition: str, configuration: str) -> str: ...
def data_provider_normalize(provider: str, request: str, rows: str) -> str: ...

class DataCredentials:
    def __init__(self, master: str, root: Path) -> None: ...
    def fix_for_task(
        self, connection: NativeConnection, sources: str, owner: str, provider: str
    ) -> str: ...
    def resolve(self, fixed: str, owner: str, spec: str) -> str: ...
    def state(self, connection: NativeConnection, sources: str, owner: str) -> str: ...
    def apply(self, connection: NativeConnection, sources: str, owner: str, update: str) -> str: ...
    def listing(self, connection: NativeConnection, sources: str) -> str: ...
    def opens(self, sealed: bytes) -> bool: ...

def data_connection_state(connection: NativeConnection, sources: str, identifier: str) -> str: ...
def data_connection_create(connection: NativeConnection, sources: str, body: str) -> str: ...
def data_connection_update(
    connection: NativeConnection, sources: str, identifier: str, body: str
) -> str: ...
def data_observation_record(
    connection: NativeConnection,
    root: Path,
    job_id: str,
    token: str,
    index: int,
    value: str,
    now: float,
) -> str: ...
def data_observation_resume(
    connection: NativeConnection, root: Path, job_id: str, token: str, now: float
) -> str: ...
def data_observation_verify(
    connection: NativeConnection, job_id: str, attempt: int, envelope: str
) -> str: ...
def data_observation_list(
    connection: NativeConnection, job_id: str, offset: int, limit: int
) -> str: ...
def data_observation_preview(
    connection: NativeConnection,
    root: Path,
    job_id: str,
    attempt: int,
    index: int,
    offset: int,
    limit: int,
) -> str: ...
def data_minute_context(context: str) -> str: ...
def data_minute_labels(context: str, contract: str, trading_day: str) -> str: ...
def data_minute_window(context: str, contract: str, trading_day: str) -> str: ...
def data_minute_bind(context: str, rows: str, observed: str) -> str: ...
def data_catalog_input_check(item: str, manifest: str) -> None: ...
def data_source_catalog(preview: str, version_id: str, symbols: str) -> str: ...
def data_product_catalog(preview: str, version_id: str, product_id: str) -> str: ...
def data_source_contract(preview: str, contract_id: str) -> str: ...
def data_sync_task_identity(payload: str) -> str: ...
def data_sync_validate_identity(connection: NativeConnection, root: Path, payload: str) -> str: ...
def data_sync_prepare(connection: NativeConnection, root: Path, submission: str) -> str: ...
def data_sync_payload(
    connection: NativeConnection, credentials: DataCredentials, request: str
) -> str: ...
def data_sync_submit(
    connection: NativeConnection,
    credentials: DataCredentials,
    root: Path,
    request: str,
    admission: str,
    now: float,
) -> str: ...
def data_sync_admit(
    connection: NativeConnection,
    credentials: DataCredentials,
    root: Path,
    submission: str,
    now: float,
) -> str: ...
def data_sync_submit_batch(
    connection: NativeConnection,
    credentials: DataCredentials,
    root: Path,
    batch: str,
    now: float,
) -> str: ...
def data_sync_collect(
    database_url: str, credentials: DataCredentials, root: Path, job: str, lease_seconds: float
) -> bytes: ...
