# Generated by scripts/generate_domain_models.py from Rust; do not edit.
# ruff: noqa
from __future__ import annotations
from datetime import date as date_type
from decimal import Decimal
from typing import ClassVar, Literal
from pydantic import AwareDatetime, ConfigDict, Field, StrictBool
from ._calendar_binding import *


class CalendarDay(CalendarModel):
    _native_model: ClassVar[str] = "CalendarDay"
    _native_fields: ClassVar[frozenset[str]] = frozenset(("date", "is_open", "night_open"))
    date: date_type
    is_open: StrictBool
    night_open: StrictBool


class ExceptionDay(CalendarModel):
    _native_model: ClassVar[str] = "ExceptionDay"
    _native_fields: ClassVar[frozenset[str]] = frozenset(("day", "night", "source", "trading_day"))
    day: tuple[Slot, ...] = Field(max_length=20)
    night: tuple[Slot, ...] = Field(max_length=20)
    source: str = Field(min_length=1, max_length=2000)
    trading_day: date_type


Exchange = Literal["SHFE", "DCE", "CZCE", "CFFEX", "INE", "GFEX"]


class Period(CalendarModel):
    _native_model: ClassVar[str] = "Period"
    _native_fields: ClassVar[frozenset[str]] = frozenset(("day", "end", "night", "source", "start"))
    day: tuple[Slot, ...] = Field(min_length=1, max_length=20)
    end: date_type
    night: tuple[Slot, ...] = Field(max_length=20)
    source: str = Field(min_length=1, max_length=2000)
    start: date_type


Phase = Literal["auction", "continuous"]
Session = Literal["day", "night"]


class Slot(CalendarModel):
    _native_model: ClassVar[str] = "Slot"
    _native_fields: ClassVar[frozenset[str]] = frozenset(("end", "end_offset", "phase", "start"))
    end: str = Field(pattern="^(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d$")
    end_offset: int = Field(ge=0, le=1)
    phase: Phase
    start: str = Field(pattern="^(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d$")


class Span(CalendarModel):
    _native_model: ClassVar[str] = "Span"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("end", "phase", "session", "start", "trading_day")
    )
    end: AwareDatetime
    phase: Phase
    session: Session
    start: AwareDatetime
    trading_day: date_type


class TimeSpec(CalendarOps, CalendarModel):
    _native_model: ClassVar[str] = "TimeSpec"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        (
            "calendar",
            "calendar_source",
            "exceptions",
            "exchange",
            "night_source",
            "periods",
            "product",
            "schema_version",
            "timezone",
            "title",
        )
    )
    calendar: tuple[CalendarDay, ...] = Field(min_length=2, max_length=3700)
    calendar_source: str = Field(min_length=1, max_length=2000)
    exceptions: tuple[ExceptionDay, ...] = Field(max_length=200)
    exchange: Exchange
    night_source: str = Field(min_length=1, max_length=2000)
    periods: tuple[Period, ...] = Field(min_length=1, max_length=100)
    product: str = Field(max_length=20, pattern="^[A-Z]+$")
    schema_version: int = Field(ge=1, le=1)
    timezone: str = Field(pattern="^Asia/Shanghai$")
    title: str = Field(min_length=1, max_length=100)


class TimeVersion(CalendarModel):
    _native_model: ClassVar[str] = "TimeVersion"
    _native_fields: ClassVar[frozenset[str]] = frozenset(("id", "spec"))
    id: str = Field(pattern="^[a-f0-9]{64}$")
    spec: TimeSpec


CalendarDay.model_rebuild()
ExceptionDay.model_rebuild()
Period.model_rebuild()
Slot.model_rebuild()
Span.model_rebuild()
TimeSpec.model_rebuild()
TimeVersion.model_rebuild()
