# Generated by scripts/generate_domain_models.py from Rust; do not edit.
# ruff: noqa
from __future__ import annotations
from datetime import date as date_type
from decimal import Decimal
from typing import ClassVar, Literal
from pydantic import AwareDatetime, ConfigDict, Field, StrictBool
from ._catalog_binding import *


class CatalogInput(CatalogModel):
    _native_model: ClassVar[str] = "CatalogInput"
    _native_fields: ClassVar[frozenset[str]] = frozenset(("checksum", "source", "version_id"))
    checksum: str = Field(pattern="^[0-9a-f]{64}$")
    source: str = Field(min_length=1, max_length=64)
    version_id: str = Field(min_length=1, max_length=100)


class Contract(CatalogModel):
    _native_model: ClassVar[str] = "Contract"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        (
            "delivery_month",
            "id",
            "last_delivery_on",
            "last_trade_on",
            "listed_on",
            "product_id",
            "provenance",
        )
    )
    delivery_month: str = Field(pattern="^[0-9]{4}-(0[1-9]|1[0-2])$")
    id: str = Field(min_length=1, max_length=100)
    last_delivery_on: date_type | None
    last_trade_on: date_type
    listed_on: date_type
    product_id: str
    provenance: Provenance


class ContractResolution(CatalogModel):
    _native_model: ClassVar[str] = "ContractResolution"
    _native_fields: ClassVar[frozenset[str]] = frozenset(("contract", "mapping"))
    contract: Contract
    mapping: SourceSymbol


Exchange = Literal["SHFE", "DCE", "CZCE", "CFFEX", "INE", "GFEX"]


class FileSymbol(CatalogModel):
    _native_model: ClassVar[str] = "FileSymbol"
    _native_fields: ClassVar[frozenset[str]] = frozenset(("contract", "source", "symbol"))
    contract: str = Field(min_length=1, max_length=100)
    source: str = Field(min_length=1, max_length=64)
    symbol: str = Field(min_length=1, max_length=64)


class ImportIdentity(ImportOps, CatalogModel):
    _native_model: ClassVar[str] = "ImportIdentity"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("bindings", "catalog", "catalog_id", "information_at")
    )
    bindings: tuple[FileSymbol, ...] = Field(min_length=1, max_length=10000)
    catalog: ReferenceCatalog
    catalog_id: str = Field(pattern="^[0-9a-f]{64}$")
    information_at: AwareDatetime


class Product(CatalogModel):
    _native_model: ClassVar[str] = "Product"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("currency", "exchange", "id", "name", "provenance")
    )
    currency: str = Field(pattern="^[A-Z]{3}$")
    exchange: Exchange
    id: str = Field(pattern="^(SHFE|DCE|CZCE|CFFEX|INE|GFEX)\\.[A-Z]+$")
    name: str = Field(min_length=1)
    provenance: Provenance


class Provenance(CatalogModel):
    _native_model: ClassVar[str] = "Provenance"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("available_at", "observed_at", "source", "source_version")
    )
    available_at: AwareDatetime
    observed_at: AwareDatetime
    source: str = Field(min_length=1)
    source_version: str = Field(min_length=1)


class ReferenceCatalog(CatalogOps, CatalogModel):
    _native_model: ClassVar[str] = "ReferenceCatalog"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("contracts", "inputs", "products", "schema_version", "symbols")
    )
    contracts: tuple[Contract, ...]
    inputs: tuple[CatalogInput, ...]
    products: tuple[Product, ...]
    schema_version: int = Field(ge=2, le=2)
    symbols: tuple[SourceSymbol, ...]


class ReferenceRelease(CatalogModel):
    _native_model: ClassVar[str] = "ReferenceRelease"
    _native_fields: ClassVar[frozenset[str]] = frozenset(("catalog", "id", "published_at"))
    catalog: ReferenceCatalog
    id: str
    published_at: float


class ResolutionRequest(CatalogModel):
    _native_model: ClassVar[str] = "ResolutionRequest"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("information_at", "source", "symbol", "trading_day")
    )
    information_at: AwareDatetime
    source: str = Field(min_length=1, max_length=64)
    symbol: str = Field(min_length=1, max_length=64)
    trading_day: date_type


class SourceIdentity(SourceOps, CatalogModel):
    _native_model: ClassVar[str] = "SourceIdentity"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("catalog", "catalog_id", "information_at", "source", "symbol")
    )
    catalog: ReferenceCatalog
    catalog_id: str
    information_at: AwareDatetime
    source: str
    symbol: str


class SourceSymbol(CatalogModel):
    _native_model: ClassVar[str] = "SourceSymbol"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("contract_id", "provenance", "source", "symbol", "valid_from", "valid_until")
    )
    contract_id: str = Field(min_length=1, max_length=100)
    provenance: Provenance
    source: str = Field(pattern="^[A-Za-z][A-Za-z0-9_.:-]{0,63}$")
    symbol: str = Field(min_length=1, max_length=64, pattern="^\\S+$")
    valid_from: date_type
    valid_until: date_type


CatalogInput.model_rebuild()
Contract.model_rebuild()
ContractResolution.model_rebuild()
FileSymbol.model_rebuild()
ImportIdentity.model_rebuild()
Product.model_rebuild()
Provenance.model_rebuild()
ReferenceCatalog.model_rebuild()
ReferenceRelease.model_rebuild()
ResolutionRequest.model_rebuild()
SourceIdentity.model_rebuild()
SourceSymbol.model_rebuild()
