# Generated by scripts/generate_domain_models.py from Rust; do not edit.
# ruff: noqa
from __future__ import annotations
from datetime import date as date_type
from decimal import Decimal
from typing import ClassVar, Literal
from pydantic import AwareDatetime, ConfigDict, Field, StrictBool
from ._connections_binding import *

Channel = Literal["market", "account"]


class ChannelState(ConnectionsModel):
    _native_model: ClassVar[str] = "ChannelState"
    _native_fields: ClassVar[frozenset[str]] = frozenset(("detail", "generation", "state"))
    detail: str = Field(default="尚未连接")
    generation: int = Field(default=0, ge=0)
    state: ConnectionStatus = Field(default="disconnected")


class ConfigField(ConnectionsModel):
    _native_model: ClassVar[str] = "ConfigField"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("default", "identity", "key", "label", "required", "secret")
    )
    default: str = Field(default="")
    identity: StrictBool = Field(default=False)
    key: str
    label: str
    required: StrictBool = Field(default=True)
    secret: StrictBool = Field(default=False)


class ConnectionProfile(ConnectionsModel):
    _native_model: ClassVar[str] = "ConnectionProfile"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("config", "config_revision", "connection_id", "connector_id", "name")
    )
    config: dict[str, str]
    config_revision: int = Field(ge=0)
    connection_id: str
    connector_id: str
    name: str


ConnectionStatus = Literal[
    "disconnected", "connecting", "authenticating", "ready", "reconnecting", "error"
]


class ConnectorDescriptor(ConnectionsModel):
    _native_model: ClassVar[str] = "ConnectorDescriptor"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("capabilities", "fields", "id", "instructions", "owner", "title", "version")
    )
    capabilities: tuple[Feature, ...]
    fields: tuple[ConfigField, ...]
    id: str
    instructions: str = Field(default="")
    owner: str
    title: str
    version: Literal[1] = Field(default=1, ge=0)


Exchange = Literal["SHFE", "DCE", "CZCE", "CFFEX", "INE", "GFEX"]
Feature = Literal["market_quotes", "instrument_catalog", "account_snapshot", "positions"]


class ReadBatch(ConnectionsModel):
    _native_model: ClassVar[str] = "ReadBatch"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("complete", "connection_id", "generation", "observed_at", "request_id", "started_at")
    )
    complete: Literal[True]
    connection_id: str
    generation: int = Field(ge=0)
    observed_at: float
    request_id: str
    started_at: float


class ReadRequest(ConnectionsModel):
    _native_model: ClassVar[str] = "ReadRequest"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("connection_id", "generation", "request_id", "started_at")
    )
    connection_id: str
    generation: int = Field(ge=0)
    request_id: str
    started_at: float


class Subscription(ConnectionsModel):
    _native_model: ClassVar[str] = "Subscription"
    _native_fields: ClassVar[frozenset[str]] = frozenset(("exchange", "symbol"))
    exchange: Exchange
    symbol: str


ChannelState.model_rebuild()
ConfigField.model_rebuild()
ConnectionProfile.model_rebuild()
ConnectorDescriptor.model_rebuild()
ReadBatch.model_rebuild()
ReadRequest.model_rebuild()
Subscription.model_rebuild()
