# Generated by scripts/generate_domain_models.py from Rust; do not edit.
# ruff: noqa
from __future__ import annotations
from datetime import date as date_type
from decimal import Decimal
from typing import ClassVar, Literal
from pydantic import AwareDatetime, ConfigDict, Field, StrictBool
from ._data_store_binding import *

Cell = None | int | str


class CoverageGap(DataStoreModel):
    _native_model: ClassVar[str] = "CoverageGap"
    _native_fields: ClassVar[frozenset[str]] = frozenset(("end", "start"))
    end: date_type
    start: date_type


class MergeRequest(DataStoreModel):
    _native_model: ClassVar[str] = "MergeRequest"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        (
            "columns",
            "job_id",
            "observed_at",
            "parent",
            "primary_key",
            "raw_version_id",
            "rows",
            "time_field",
            "type_id",
        )
    )
    columns: tuple[str, ...] = Field(min_length=1, max_length=126)
    job_id: str = Field(min_length=1, max_length=128)
    observed_at: tuple[str, ...]
    parent: ParentVersion | None
    primary_key: tuple[str, ...] = Field(min_length=1, max_length=16)
    raw_version_id: str = Field(min_length=1, max_length=256)
    rows: tuple[tuple[Cell, ...], ...] = Field(min_length=1, max_length=1000000)
    time_field: str
    type_id: str


class ParentVersion(DataStoreModel):
    _native_model: ClassVar[str] = "ParentVersion"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("coverage_gaps", "first", "id", "index", "last", "observed_at", "revision")
    )
    coverage_gaps: tuple[CoverageGap, ...] | None
    first: str
    id: str = Field(min_length=1, max_length=256)
    index: PartitionedVersion
    last: str
    observed_at: str
    revision: int = Field(ge=1)


class Partition(DataStoreModel):
    _native_model: ClassVar[str] = "Partition"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("bytes", "checksum", "first", "inputs", "key", "last", "replaces", "rows")
    )
    bytes: int = Field(ge=1)
    checksum: str
    first: str
    inputs: tuple[str, ...]
    key: str = Field(min_length=1, max_length=256)
    last: str
    replaces: str | None
    rows: int = Field(ge=0)


class PartitionedVersion(DataStoreModel):
    _native_model: ClassVar[str] = "PartitionedVersion"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("bytes", "checksum", "partitions", "path")
    )
    bytes: int = Field(ge=1)
    checksum: str
    partitions: tuple[Partition, ...]
    path: str


class ScanRequest(DataStoreModel):
    _native_model: ClassVar[str] = "ScanRequest"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("batch_rows", "columns", "contract_ids", "end", "start", "version_id")
    )
    batch_rows: int = Field(default=1024, ge=1, le=4096)
    columns: tuple[str, ...] = Field(min_length=1, max_length=30)
    contract_ids: tuple[str, ...] = Field(min_length=1, max_length=1000)
    end: date_type
    start: date_type
    version_id: str = Field(min_length=1, max_length=256)


CoverageGap.model_rebuild()
MergeRequest.model_rebuild()
ParentVersion.model_rebuild()
Partition.model_rebuild()
PartitionedVersion.model_rebuild()
ScanRequest.model_rebuild()
