# Generated by scripts/generate_domain_models.py from Rust; do not edit.
# ruff: noqa
from __future__ import annotations
from datetime import date as date_type
from decimal import Decimal
from typing import ClassVar, Literal
from pydantic import AwareDatetime, ConfigDict, Field, StrictBool
from ._execution_binding import *

from .rules import (
    AvailabilityAssumption,
    ContractBasis,
    FeeField,
    FeeMode,
    FeeScope,
    FeeUnit,
    MarginUnit,
    RulePeriod,
    RuleSpec,
    RuleVersion,
    SettlementBasis,
    SettlementEvidence,
    SettlementRow,
)
from .calendar import CalendarDay, ExceptionDay, Period, Phase, Slot, TimeSpec, TimeVersion
from .catalog import Contract, Exchange, Provenance


class AccountEvent(ExecutionModel):
    _native_model: ClassVar[str] = "AccountEvent"
    _native_fields: ClassVar[frozenset[str]] = frozenset(("contract_id", "day", "reason"))
    contract_id: str
    day: date_type
    reason: str


class ClosedBar(ExecutionModel):
    _native_model: ClassVar[str] = "ClosedBar"
    _native_fields: ClassVar[frozenset[str]] = frozenset(("close", "trading_day"))
    close: Decimal
    trading_day: date_type


class CurvePoint(ExecutionModel):
    _native_model: ClassVar[str] = "CurvePoint"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        (
            "balance",
            "close_equity",
            "close_pnl",
            "contract_id",
            "day",
            "drawdown",
            "equity",
            "fees",
            "free_cash",
            "margin",
            "margin_rate",
            "next_target",
            "opening_balance",
            "position",
            "session_close",
            "session_open",
            "settle",
            "settlement_pnl",
            "time_version",
        )
    )
    balance: Decimal
    close_equity: Decimal
    close_pnl: Decimal
    contract_id: str
    day: date_type
    drawdown: Decimal
    equity: Decimal
    fees: Decimal
    free_cash: Decimal
    margin: Decimal
    margin_rate: Decimal
    next_target: int
    opening_balance: Decimal
    position: int
    session_close: str
    session_open: str
    settle: Decimal
    settlement_pnl: Decimal
    time_version: str


class DailyBar(ExecutionModel):
    _native_model: ClassVar[str] = "DailyBar"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("close", "contract", "contract_id", "open", "settle", "trading_day")
    )
    close: Decimal
    contract: str
    contract_id: str
    open: Decimal
    settle: Decimal
    trading_day: date_type


class DailyPrices(ExecutionModel):
    _native_model: ClassVar[str] = "DailyPrices"
    _native_fields: ClassVar[frozenset[str]] = frozenset(("close", "high", "low", "open", "settle"))
    close: Decimal
    high: Decimal
    low: Decimal
    open: Decimal
    settle: Decimal


class ExecutionConfig(ExecutionModel):
    _native_model: ClassVar[str] = "ExecutionConfig"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("capital", "end", "lots", "rules", "slippage_ticks", "start")
    )
    capital: Decimal
    end: date_type
    lots: int = Field(ge=1, le=1000)
    rules: RuleVersion
    slippage_ticks: int = Field(ge=0, le=100)
    start: date_type


class ExecutionResult(ExecutionModel):
    _native_model: ClassVar[str] = "ExecutionResult"
    _native_fields: ClassVar[frozenset[str]] = frozenset(("curve", "events", "fills", "summary"))
    curve: tuple[CurvePoint, ...]
    events: tuple[AccountEvent, ...]
    fills: tuple[Fill, ...]
    summary: Summary


class Fill(ExecutionModel):
    _native_model: ClassVar[str] = "Fill"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        (
            "contract_id",
            "day",
            "fee",
            "fee_mode",
            "fee_rate",
            "lots",
            "price",
            "reason",
            "rule_start",
            "rule_version",
            "side",
            "time",
        )
    )
    contract_id: str
    day: date_type
    fee: Decimal
    fee_mode: FeeMode
    fee_rate: Decimal
    lots: int
    price: Decimal
    reason: str
    rule_start: date_type
    rule_version: str
    side: str
    time: str


class Summary(ExecutionModel):
    _native_model: ClassVar[str] = "Summary"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        (
            "bars",
            "contract_id",
            "fees",
            "fill_count",
            "final_equity",
            "initial_equity",
            "max_drawdown",
            "net_profit",
            "open_lots",
            "return_rate",
        )
    )
    bars: int = Field(ge=0)
    contract_id: str
    fees: Decimal
    fill_count: int = Field(ge=0)
    final_equity: Decimal
    initial_equity: Decimal
    max_drawdown: Decimal
    net_profit: Decimal
    open_lots: int
    return_rate: Decimal


AccountEvent.model_rebuild()
ClosedBar.model_rebuild()
CurvePoint.model_rebuild()
DailyBar.model_rebuild()
DailyPrices.model_rebuild()
ExecutionConfig.model_rebuild()
ExecutionResult.model_rebuild()
Fill.model_rebuild()
Summary.model_rebuild()
