# Generated by scripts/generate_domain_models.py from Rust; do not edit.
# ruff: noqa
from __future__ import annotations
from datetime import date as date_type
from decimal import Decimal
from typing import ClassVar, Literal
from pydantic import AwareDatetime, ConfigDict, Field, StrictBool
from ._market_feed_binding import *


class Quote(MarketFeedModel):
    _native_model: ClassVar[str] = "Quote"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        (
            "action_day",
            "change",
            "change_percent",
            "event_at",
            "exchange",
            "high",
            "last",
            "low",
            "open_interest",
            "previous_settlement",
            "received_at",
            "source_time",
            "stale",
            "status",
            "symbol",
            "trading_day",
            "volume",
        )
    )
    action_day: str
    change: float | None
    change_percent: float | None
    event_at: float | None
    exchange: str
    high: float | None
    last: float | None
    low: float | None
    open_interest: float | None
    previous_settlement: float | None
    received_at: float
    source_time: str
    stale: StrictBool
    status: QuoteStatus
    symbol: str
    trading_day: str
    volume: int | None


class QuoteEvent(MarketFeedModel):
    _native_model: ClassVar[str] = "QuoteEvent"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        (
            "action_day",
            "event_at",
            "exchange",
            "high",
            "last",
            "low",
            "open_interest",
            "previous_settlement",
            "received_at",
            "source_time",
            "symbol",
            "trading_day",
            "volume",
        )
    )
    action_day: str
    event_at: float | None
    exchange: str
    high: float | None
    last: float | None
    low: float | None
    open_interest: float | None
    previous_settlement: float | None
    received_at: float
    source_time: str
    symbol: str
    trading_day: str
    volume: int | None


QuoteStatus = Literal[
    "current", "disconnected", "time_unknown", "time_ahead", "not_updated", "delayed"
]

Quote.model_rebuild()
QuoteEvent.model_rebuild()
