# Generated by scripts/generate_domain_models.py from Rust; do not edit.
# ruff: noqa
from __future__ import annotations
from datetime import date as date_type
from decimal import Decimal
from typing import ClassVar, Literal
from pydantic import AwareDatetime, ConfigDict, Field, StrictBool
from ._roles_binding import *

from .calendar import (
    CalendarDay,
    ExceptionDay,
    Period,
    Phase,
    Session,
    Slot,
    Span,
    TimeSpec,
    TimeVersion,
)
from .catalog import (
    CatalogInput,
    Contract,
    Exchange,
    Product,
    Provenance,
    ReferenceCatalog,
    SourceSymbol,
)

AvailabilityBasis = Literal["local_observation"]


class ComputedAssignment(RolesModel):
    _native_model: ClassVar[str] = "ComputedAssignment"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("available_at", "effective_day", "effective_start", "main", "secondary")
    )
    model_config = ConfigDict(str_strip_whitespace=True)
    available_at: AwareDatetime
    effective_day: date_type
    effective_start: AwareDatetime
    main: str = Field(min_length=1)
    secondary: str = Field(min_length=1)


class ComputedRoleIndex(ComputedRoleOps, RolesModel):
    _native_model: ClassVar[str] = "ComputedRoleIndex"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("catalog", "product_id", "published_at", "records", "trading_time", "version_id")
    )
    model_config = ConfigDict(str_strip_whitespace=True)
    catalog: ReferenceCatalog
    product_id: str
    published_at: AwareDatetime
    records: tuple[ComputedAssignment, ...] = Field(min_length=1, max_length=1000)
    trading_time: TimeVersion
    version_id: str = Field(pattern="^[a-f0-9]{64}$")


class ComputedRoleResolution(RolesModel):
    _native_model: ClassVar[str] = "ComputedRoleResolution"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        (
            "availability_basis",
            "available_at",
            "contract",
            "execution_authorized",
            "historical_publication_attested",
            "record_index",
            "session",
            "version_id",
        )
    )
    model_config = ConfigDict(str_strip_whitespace=True)
    availability_basis: AvailabilityBasis
    available_at: AwareDatetime
    contract: Contract
    execution_authorized: Literal[False]
    historical_publication_attested: Literal[False]
    record_index: int = Field(ge=0)
    session: Span
    version_id: str


Exchange2 = Literal["SHFE", "DCE", "CZCE", "CFFEX", "INE", "GFEX"]


class NextOpening(RolesModel):
    _native_model: ClassVar[str] = "NextOpening"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("available_at", "observation_end", "product_id", "trading_time")
    )
    model_config = ConfigDict(str_strip_whitespace=True)
    available_at: AwareDatetime
    observation_end: AwareDatetime
    product_id: str
    trading_time: TimeVersion


Role = Literal["main", "secondary"]


class RoleCalendar(OpeningOps, RolesModel):
    _native_model: ClassVar[str] = "RoleCalendar"
    _native_fields: ClassVar[frozenset[str]] = frozenset(("product_id", "trading_time"))
    model_config = ConfigDict(str_strip_whitespace=True)
    product_id: str
    trading_time: TimeVersion


RoleMode = Literal["as_known", "retrospective"]
RoleOrigin = Literal["provider_report"]


class RoleQuery(RolesModel):
    _native_model: ClassVar[str] = "RoleQuery"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("explanation", "information_at", "mode", "role", "timestamp", "version_id")
    )
    model_config = ConfigDict(str_strip_whitespace=True)
    explanation: str = Field(max_length=2000)
    information_at: AwareDatetime
    mode: RoleMode
    role: Role
    timestamp: AwareDatetime
    version_id: str = Field(pattern="^[a-f0-9]{64}$")


class RoleReport(RolesModel):
    _native_model: ClassVar[str] = "RoleReport"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("available_at", "contract_id", "evidence", "role", "trading_day")
    )
    model_config = ConfigDict(str_strip_whitespace=True)
    available_at: AwareDatetime | None
    contract_id: str = Field(min_length=1)
    evidence: str = Field(min_length=1, max_length=2000)
    role: Role
    trading_day: date_type


class RoleResolution(RolesModel):
    _native_model: ClassVar[str] = "RoleResolution"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        (
            "contract",
            "execution_authorized",
            "explanation",
            "mode",
            "report",
            "session",
            "version_id",
        )
    )
    model_config = ConfigDict(str_strip_whitespace=True)
    contract: Contract
    execution_authorized: Literal[False]
    explanation: str
    mode: RoleMode
    report: RoleReport
    session: Span
    version_id: str


class RoleSpec(RolesModel):
    _native_model: ClassVar[str] = "RoleSpec"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        (
            "catalog",
            "observed_at",
            "origin",
            "product_id",
            "reports",
            "schema_version",
            "source",
            "source_checksum",
            "source_version",
            "trading_time",
        )
    )
    model_config = ConfigDict(str_strip_whitespace=True)
    catalog: ReferenceCatalog
    observed_at: AwareDatetime
    origin: RoleOrigin
    product_id: str
    reports: tuple[RoleReport, ...] = Field(min_length=1, max_length=10000)
    schema_version: int = Field(ge=1, le=1)
    source: str = Field(min_length=1, max_length=100)
    source_checksum: str = Field(pattern="^[a-f0-9]{64}$")
    source_version: str = Field(min_length=1, max_length=100)
    trading_time: TimeVersion


class RoleVersion(RolesModel):
    _native_model: ClassVar[str] = "RoleVersion"
    _native_fields: ClassVar[frozenset[str]] = frozenset(("id", "spec"))
    model_config = ConfigDict(str_strip_whitespace=True)
    id: str = Field(pattern="^[a-f0-9]{64}$")
    spec: RoleSpec


ComputedAssignment.model_rebuild()
ComputedRoleIndex.model_rebuild()
ComputedRoleResolution.model_rebuild()
NextOpening.model_rebuild()
RoleCalendar.model_rebuild()
RoleQuery.model_rebuild()
RoleReport.model_rebuild()
RoleResolution.model_rebuild()
RoleSpec.model_rebuild()
RoleVersion.model_rebuild()
