# Generated by scripts/generate_domain_models.py from Rust; do not edit.
# ruff: noqa
from __future__ import annotations
from datetime import date as date_type
from decimal import Decimal
from typing import ClassVar, Literal
from pydantic import AwareDatetime, ConfigDict, Field, StrictBool
from ._rules_binding import *

from .calendar import CalendarDay, ExceptionDay, Period, Phase, Slot, TimeSpec, TimeVersion
from .catalog import Contract, Exchange, Provenance

AvailabilityAssumption = Literal["after_source_day"]


class ContractBasis(RulesModel):
    _native_model: ClassVar[str] = "ContractBasis"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        (
            "checksum",
            "connection_id",
            "contract_id",
            "delisted",
            "exchange",
            "listed",
            "multiplier",
            "name",
            "per_unit",
            "provider",
            "quote_unit",
            "quote_unit_desc",
            "symbol",
            "trade_unit",
            "version_id",
        )
    )
    checksum: str = Field(pattern="^[a-f0-9]{64}$")
    connection_id: str | None = Field(pattern="^c_[0-9a-f]{32}$")
    contract_id: str = Field(
        pattern="^(SHFE|DCE|CZCE|CFFEX|INE|GFEX)\\.[A-Z]+\\.[0-9]{6}\\.[0-9]{8}$"
    )
    delisted: date_type | None
    exchange: str = Field(min_length=1, max_length=10)
    listed: date_type
    multiplier: str | None
    name: str = Field(min_length=1, max_length=200)
    per_unit: str | None
    provider: str = Field(min_length=1, max_length=100)
    quote_unit: str | None
    quote_unit_desc: str | None
    symbol: str = Field(min_length=1, max_length=30)
    trade_unit: str | None
    version_id: str = Field(min_length=1, max_length=100)


FeeField = Literal["trading_fee", "trading_fee_rate"]
FeeMode = Literal["per_lot", "notional"]
FeeScope = Literal["long_open_and_non_today_close"]
FeeUnit = Literal["yuan_per_lot", "ratio", "percent", "permille", "permyriad"]
MarginUnit = Literal["ratio", "percent"]


class RulePeriod(RulePeriodOps, RulesModel):
    _native_model: ClassVar[str] = "RulePeriod"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("close_fee", "end", "fee_mode", "margin_rate", "open_fee", "settlement_basis", "start")
    )
    close_fee: Decimal
    end: date_type
    fee_mode: FeeMode
    margin_rate: Decimal
    open_fee: Decimal
    settlement_basis: SettlementBasis | None
    start: date_type


class RuleSpec(RulesOps, RulesModel):
    _native_model: ClassVar[str] = "RuleSpec"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        (
            "basis",
            "contract",
            "multiplier",
            "periods",
            "source",
            "tick_size",
            "title",
            "trading_time",
        )
    )
    model_config = ConfigDict(str_strip_whitespace=True)
    basis: ContractBasis | None
    contract: Contract
    multiplier: Decimal
    periods: tuple[RulePeriod, ...] = Field(min_length=1, max_length=100)
    source: str = Field(min_length=1, max_length=1000)
    tick_size: Decimal
    title: str = Field(min_length=1, max_length=100)
    trading_time: TimeVersion


class RuleVersion(RulesModel):
    _native_model: ClassVar[str] = "RuleVersion"
    _native_fields: ClassVar[frozenset[str]] = frozenset(("id", "spec"))
    id: str = Field(pattern="^[a-f0-9]{64}$")
    spec: RuleSpec


class SettlementBasis(SettlementOps, RulesModel):
    _native_model: ClassVar[str] = "SettlementBasis"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        (
            "availability_assumption",
            "evidence",
            "fee_field",
            "fee_scope",
            "fee_unit",
            "interpretation",
            "margin_unit",
        )
    )
    model_config = ConfigDict(str_strip_whitespace=True)
    availability_assumption: AvailabilityAssumption
    evidence: SettlementEvidence
    fee_field: FeeField
    fee_scope: FeeScope
    fee_unit: FeeUnit
    interpretation: str = Field(min_length=1, max_length=1000)
    margin_unit: MarginUnit


class SettlementEvidence(RulesModel):
    _native_model: ClassVar[str] = "SettlementEvidence"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        ("checksum", "connection_id", "contract", "observed_at", "provider", "row", "version_id")
    )
    checksum: str = Field(pattern="^[a-f0-9]{64}$")
    connection_id: str | None = Field(pattern="^c_[0-9a-f]{32}$")
    contract: Contract
    observed_at: AwareDatetime
    provider: str = Field(min_length=1, max_length=100)
    row: SettlementRow
    version_id: str = Field(min_length=1, max_length=100)


class SettlementRow(RulesModel):
    _native_model: ClassVar[str] = "SettlementRow"
    _native_fields: ClassVar[frozenset[str]] = frozenset(
        (
            "b_hedging_margin_rate",
            "contract",
            "delivery_fee",
            "exchange",
            "long_margin_rate",
            "offset_today_fee",
            "s_hedging_margin_rate",
            "settle",
            "short_margin_rate",
            "symbol",
            "trading_day",
            "trading_fee",
            "trading_fee_rate",
        )
    )
    b_hedging_margin_rate: Decimal | None
    contract: str
    delivery_fee: Decimal | None
    exchange: str
    long_margin_rate: Decimal | None
    offset_today_fee: Decimal | None
    s_hedging_margin_rate: Decimal | None
    settle: Decimal | None
    short_margin_rate: Decimal | None
    symbol: str
    trading_day: date_type
    trading_fee: Decimal | None
    trading_fee_rate: Decimal | None


ContractBasis.model_rebuild()
RulePeriod.model_rebuild()
RuleSpec.model_rebuild()
RuleVersion.model_rebuild()
SettlementBasis.model_rebuild()
SettlementEvidence.model_rebuild()
SettlementRow.model_rebuild()
